export const skillsData = [
  {
    id: 1,
    name: 'ReactJS',
    status: 'Completed',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/2300px-React-icon.svg.png',
    icon: 'assets/twitter.png',
  },
  {
    id: 2,
    name: 'NextJS',
    status: 'Running...',
    img: 'https://miro.medium.com/v2/resize:fit:1400/1*BQZAbczBfLYtPp-6HmN0ZQ.jpeg',
    icon: 'assets/youtube.png',

    featured: true,
  },
  {
    id: 3,
    name: 'Javascript',
    status: 'Completed',
    img: 'https://static-00.iconduck.com/assets.00/javascript-js-icon-2048x2048-nyxvtvk0.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 4,
    name: 'MaterialUI',
    status: 'Completed',
    img: 'https://static-00.iconduck.com/assets.00/material-ui-icon-2048x1626-on580ia9.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 5,
    name: 'Styled Components',
    status: 'Completed',
    img: 'https://www.daggala.com/static/228867c3668e439101821568a8a03b54/ec333/sc.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 6,
    name: 'Framer Motion',
    status: 'Completed',
    img: 'https://www.ejable.com/wp-content/uploads/2022/04/Framer-Motion.webp',
    icon: 'assets/linkedin.png',
  },
  {
    id: 7,
    name: 'TailwindCSS',
    status: 'Completed',
    img: 'https://static-00.iconduck.com/assets.00/tailwind-css-icon-1024x615-fdeis5r1.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 8,
    name: 'Atomic CSS',
    status: 'Completed',
    img: 'https://sebastienlorber.com/static/80100b6831efdf60fa68f366b41413a6/6050d/hero.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 9,
    name: 'Design Patterns',
    status: 'Running',
    img: 'https://miro.medium.com/v2/resize:fit:1400/1*foVnq6ka4jPqrOzWWhq1kA.png',
    icon: 'assets/linkedin.png',
  },

  {
    id: 10,
    name: 'HTML',
    status: 'Completed',
    img: 'https://cdn.iconscout.com/icon/premium/png-256-thumb/html-2752158-2284975.png?f=webp&w=256',
    icon: 'assets/linkedin.png',
  },
  {
    id: 11,
    name: 'Redux',
    status: 'Completed',
    img: 'https://w7.pngwing.com/pngs/273/105/png-transparent-redux-original-logo-icon.png',
    icon: 'assets/linkedin.png',
  },
  {
    id: 12,
    name: 'Git',
    status: 'Completed',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/2048px-Git_icon.svg.png',
    icon: 'assets/linkedin.png',
  },
];

export const navArray = [
  { id: 1, path: '/', name: 'Home' },
  { id: 2, path: '/projects', name: 'Projects' },
  { id: 3, path: '/about', name: 'About' },
  { id: 4, path: '/skills', name: 'Skills' },
  { id: 5, path: '/contact', name: 'Contact' },
];

export const projectsData = [
  {
    id: 1,
    category: 'NextJS',
    title: 'Dreams Food',
    description:
      'In this project i try to implement various functionality through, react, node.js, mongoDB and express.js',
    technologies: ['React', 'Node.js', 'MongoDB', 'Express.js'],
    screenshots: [
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
    ],
    demoLink: 'https://example.com/demo',
    githubLink: 'https://github.com/Nazim6269/Dreams_Food-MERN',
  },
  {
    id: 2,
    category: 'ReactJS',
    title: 'Expense Tracker',
    description:
      'In this project i try to implement various functionality through, react, ',
    technologies: ['React', 'Express', 'MongoDB'],
    screenshots: [
      '/projectImages/ssExpenseTracker.png',
      '/projectImages/ssExpenseTracker.png',
    ],
    demoLink: 'https://context-api-expensetracker6269.netlify.app/',
    githubLink: 'https://github.com/Nazim6269/Expense_Tracker_Context_Api',
  },
  {
    id: 3,
    category: 'HTML-CSS',
    title: 'Social Media App',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
  {
    id: 4,
    category: 'Random',
    title: 'Rampa UI Design',
    img: 'https://cdn.dribbble.com/users/702789/screenshots/15054318/media/4ea5d492b7b07eebc9528ff960794879.png?compress=1&resize=1200x900',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
  {
    id: 4,
    category: 'MERN',
    title: 'E-commerce Web Design',
    img: 'https://cdn.dribbble.com/users/1387827/screenshots/15466426/media/deb2dca6762cd3610321c98bfccb0b72.png?compress=1&resize=1200x900',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
  {
    id: 5,
    category: 'NextJS',
    title: 'Relax Mobile App',
    img: 'https://cdn.dribbble.com/users/4095861/screenshots/15467417/media/d6a15c416626f12b31fa5ca1db192572.png?compress=1&resize=1200x900',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
  {
    id: 6,
    category: 'NextJS',
    title: 'Hero Web Design',
    img: 'https://cdn.dribbble.com/users/5031392/screenshots/15467520/media/c36b3b15b25b1e190d081abdbbf947cf.png?compress=1&resize=1200x900',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
  {
    id: 7,
    category: 'NextJS',
    title: 'Banking App',
    img: 'https://cdn.dribbble.com/users/3307260/screenshots/15468444/media/447b4501f7a145b05e11c70199a9c417.jpg?compress=1&resize=1200x900',
    description: 'lorem',
    technologies: ['react,nextjs,tailwindcss'],
    screenshots: ['abc.jpg', 'xyz.png'],
    demoLink: 'ab.com',
    githubLink: 'github.io',
  },
];
